---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
collections: 
upload_dir: assets
public_path: "/assets"
front_matter_path: "/assets"
use_front_matter_path: false
file_template: ":year:/:filename:"
